language: cpp

sudo: required
dist: trusty

matrix:
    include:
        - compiler: clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libncurses5-dev libreadline-dev nettle-dev libgnutls28-dev libtorrent-rasterbar-dev wget

before_script:
  - wget https://github.com/msgpack/msgpack-c/releases/download/cpp-1.3.0/msgpack-1.3.0.tar.gz
  - tar -xzf msgpack-1.3.0.tar.gz
  - cd msgpack-1.3.0 && mkdir build && cd build
  - cmake -DMSGPACK_CXX11=ON -DMSGPACK_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j
  - sudo make install
  - wget https://github.com/savoirfairelinux/opendht/archive/master.tar.gz
  - tar -xzf master.tar.gz
  - cd opendht-master && mkdir build && cd build
  - cmake -DOPENDHT_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j
  - sudo make install

script:
  - cmake
  - make
